repos:
  - repo: https://github.com/biomejs/pre-commit
    rev: v2.0.0-beta.1 # Use the sha / tag you want to point at
    hooks:
      - id: biome-check
        args: ["check", "--fix", "--unsafe"]
        types: [ts, tsx]
        files: ^(apps/server/|test/).*\.(ts|tsx)$