name = "code-push-server"
main = "src/index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

[observability.logs]
enabled = true

[env.local]
d1_databases = [
  { binding = "DB", database_name = "codepush-server-local", database_id = "n/a", migrations_dir = "drizzle/migrations" },
]
r2_buckets = [
 {binding= "STORAGE_BUCKET", bucket_name="code-push-storage", preview_bucket_name = "code-push-storage-dev"}
]
[env.local.vars]
SERVER_URL = "http://localhost:8787"
ENABLE_ACCOUNT_REGISTRATION = "true"
CORS_ORIGINS = "http://localhost:5173"
ENABLE_PACKAGE_DIFFING = "true"
GITHUB_CLIENT_ID="Ov23liuoVBhHRJ02UweV"


[env.production]
name = "code-push-server-preview"
d1_databases = [
  { binding = "DB", database_name = "codepush-server-prod", database_id = "aee5850e-b85e-47c6-a0fb-782591e47e5d", migrations_dir = "drizzle/migrations" },
]
r2_buckets = [
 {binding= "STORAGE_BUCKET", bucket_name="code-push-storage", preview_bucket_name = "code-push-storage-dev"}
]
[env.production.vars]
SERVER_URL="https://code-push-server-preview.yplabs.workers.dev"
ENABLE_ACCOUNT_REGISTRATION = "true"
CORS_ORIGINS = "http://localhost:3000"
ENABLE_PACKAGE_DIFFING = "true"
GITHUB_CLIENT_ID="Ov23liyNc4o1iJYk03YU"
R2_BUCKET_NAME="code-push-storage"
ACCOUNT_ID="3ed9862a49fe75464126e11a462fd26e"
AWS_REGION = "ap-northeast-2"
AWS_S3_BUCKET_NAME = "code-push-prod"